using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ClassIsland.SettingsSearchGenerator;

/// <summary>
/// 读取设置页 XAML（通过 AdditionalFiles），把每个 <c>SettingsCard</c> 的标题/描述/标签连同
/// 预生成的拼音烘焙成一个静态数组，设置搜索直接查表，运行时无需拼音库、也无需实例化页面。
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SettingsSearchGenerator : IIncrementalGenerator
{
    private static readonly Regex PageInfoRegex =
        new(@"\[SettingsPageInfo\(\s*""([^""]*)""\s*,\s*""([^""]*)""", RegexOptions.Compiled);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var files = context.AdditionalTextsProvider
            .Where(static file => IsSettingPageFile(file.Path))
            .Collect();

        context.RegisterSourceOutput(files, static (spc, texts) => Execute(spc, texts));
    }

    private static bool IsSettingPageFile(string path)
    {
        var normalized = path.Replace('\\', '/');
        return normalized.Contains("/Views/SettingPages/") &&
               (normalized.EndsWith(".xaml", StringComparison.OrdinalIgnoreCase) ||
                normalized.EndsWith(".xaml.cs", StringComparison.OrdinalIgnoreCase));
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<AdditionalText> texts)
    {
        var byPath = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var text in texts)
        {
            byPath[text.Path.Replace('\\', '/')] = text.GetText(context.CancellationToken)?.ToString() ?? "";
        }

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("namespace ClassIsland.Helpers");
        builder.AppendLine("{");
        builder.AppendLine("    internal static class SettingsSearchGenerated");
        builder.AppendLine("    {");
        builder.AppendLine("        public static readonly SettingsSearchEntry[] Entries =");
        builder.AppendLine("        {");

        foreach (var pair in byPath.Where(p => p.Key.EndsWith(".xaml", StringComparison.OrdinalIgnoreCase))
                     .OrderBy(p => p.Key, StringComparer.Ordinal))
        {
            var xamlPath = pair.Key;
            var xaml = pair.Value;
            if (!byPath.TryGetValue(xamlPath + ".cs", out var codeBehind))
            {
                continue;
            }

            var match = PageInfoRegex.Match(codeBehind);
            if (!match.Success)
            {
                continue;
            }

            var pageId = match.Groups[1].Value;
            var pageName = match.Groups[2].Value;

            // 页面本身也作为一条结果（可跳转到页面顶部）。
            AppendEntry(builder, pageId, pageName, pageName, "", "", 0, true);

            XDocument document;
            try
            {
                document = XDocument.Parse(xaml);
            }
            catch
            {
                continue;
            }

            var occurrences = new Dictionary<string, int>();
            foreach (var element in document.Descendants().Where(e => e.Name.LocalName == "SettingsCard"))
            {
                var header = (string?)element.Attribute("Header");
                if (string.IsNullOrWhiteSpace(header) || header!.StartsWith("{", StringComparison.Ordinal))
                {
                    continue;
                }

                var description = (string?)element.Attribute("Description") ?? "";
                var tags = (string?)element.Attribute("SearchTags") ?? "";

                occurrences.TryGetValue(header, out var occurrence);
                occurrences[header] = occurrence + 1;

                AppendEntry(builder, pageId, pageName, header, description, tags, occurrence, false);
            }
        }

        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        context.AddSource("SettingsSearchGenerated.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private static void AppendEntry(StringBuilder builder, string pageId, string pageName, string header,
        string description, string tags, int occurrence, bool isPage)
    {
        // 拼音只从标题+标签生成：描述太长，混进拼音会给模糊匹配引入噪声。
        var text = header + " " + tags;
        builder.Append("            new SettingsSearchEntry { PageId = ").Append(Literal(pageId))
            .Append(", PageName = ").Append(Literal(pageName))
            .Append(", Header = ").Append(Literal(header))
            .Append(", Description = ").Append(Literal(description))
            .Append(", Tags = ").Append(Literal(tags))
            .Append(", IsPage = ").Append(isPage ? "true" : "false")
            .Append(", Occurrence = ").Append(occurrence.ToString(System.Globalization.CultureInfo.InvariantCulture))
            .Append(", Pinyin = ").Append(Literal(PinyinMap.ToPinyin(text)))
            .Append(", PinyinSpaced = ").Append(Literal(PinyinMap.ToSpacedPinyin(text)))
            .Append(", Initials = ").Append(Literal(PinyinMap.ToInitials(text)))
            .AppendLine(" },");
    }

    private static string Literal(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var c in value)
        {
            switch (c)
            {
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '"':
                    builder.Append("\\\"");
                    break;
                case '\n':
                    builder.Append("\\n");
                    break;
                case '\r':
                    builder.Append("\\r");
                    break;
                case '\t':
                    builder.Append("\\t");
                    break;
                default:
                    if (c < 0x20 || c > 0x7E)
                    {
                        builder.Append("\\u").Append(((int)c).ToString("x4"));
                    }
                    else
                    {
                        builder.Append(c);
                    }

                    break;
            }
        }

        return builder.Append('"').ToString();
    }
}
