<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>12</LangVersion>
		<Title>LegacyIsland Plugin SDK</Title>
		<Configurations>Debug;Release;Debug_MSIX;Release_MSIX</Configurations>
	</PropertyGroup>

	<PropertyGroup>
	  <PackageTags>legacyisland;plugin;addin;wpf;material design</PackageTags>
	  <Description>用于开发应用 LegacyIsland 插件的 SDK。</Description>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ClassIsland.Core\ClassIsland.Core.csproj" IncludeAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Properties\" />
		<None Include="ClassIsland.PluginSdk.targets" Pack="True" PackagePath="build/net472" />
		<None Include="generate-md5.ps1" Pack="True" PackagePath="build/net472" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="DotNetCampus.LatestCSharpFeatures" Version="13.0.1" />
	</ItemGroup>
	
	<Import Project="..\GeneratePackage.props" />
	<Import Project="..\Global.props" />
	<Import Project=".\ClassIsland.PluginSdk.targets" />
</Project>
