<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <LangVersion>12</LangVersion>
	  <Configurations>Debug;Release;Debug_MSIX;Release_MSIX</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetCampus.LatestCSharpFeatures" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ClassIsland.Shared.IPC\ClassIsland.Shared.IPC.csproj" />
    <ProjectReference Include="..\..\ClassIsland.Shared\ClassIsland.Shared.csproj" />
  </ItemGroup>

</Project>
