<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="DotNetCampus.LatestCSharpFeatures" Version="13.0.1" />
		<PackageReference Include="Strings.ResourceGenerator" Version="0.6.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<AdditionalFiles Include="SR.strings" />
	</ItemGroup>
</Project>
